### PR TITLE
Add term publishing plugin commands to charm snap.

### PR DESCRIPTION
**Pull request by cmars**
This adds plugin commands for users to be able to publish their own terms:
`charm push-term`
`charm publish-term`
`charm show-term`

### CODE REVIEW

**Comment by cmars** [comment]
Marking this WIP as the following need to land & get tagged first:
juju/charmstore-client#89
juju/terms-client#10

**Comment by marcoceppi** [comment]
FWIW, this :+1: pending the changes outlined above. I'll wait for those to land and try to get travis set up for snap build testing

**Comment by cmars** [comment]
@marcoceppi Dependent PRs have landed, updated build tags accordingly, ready to land.

**Comment by marcoceppi** [comment]
LGTM :boat:

**Pull request merged**
